<?php

declare(strict_types=1);

use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;
use MaxStan\Mercure\ViewModel\AdminJwtToken;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var AdminJwtToken $viewModel */
$viewModel = $block->getData('viewModel');
?>
<script>
    const worker = new SharedWorker('<?= $block->getViewFileUrl('MaxStan_Mercure::js/admin-worker.js') ?>');
    worker.port.addEventListener('message', function (event) {
        const message = event.data;
        if (!message || !message.event) {
            return;
        }

        window.dispatchEvent(
            new CustomEvent('admin-mercure:' + message.event, { detail: message.data })
        );
    });
    worker.port.start();

    worker.port.postMessage({ type: 'authorize', token: '<?= $escaper->escapeJs($viewModel->getJwt()) ?>' });
    window.mercureWorkerPort = worker.port;
</script>
